// Companion island geometry constants.
export const COMPACT_W = 288
export const EXPANDED_W = 640
export const ROUNDED_CORNER = 14
export const EXPANDED_CORNER = 22
export const OVERVIEW_H = 160
export const GREETING_H = 150
export const OVERVIEW_BOT_DIAMETER = 58
export const APPROVAL_BOT_DIAMETER = 56
export const GREETING_BOT_DIAMETER = 0
export const TOOL_CARD_H = 104
export const USAGE_CARD_H = 84
