import { describe, expect, it } from 'vitest'
import { isOutfit, normalizeOutfit, resolveOutfit, seasonalOutfit } from './outfit'

describe('outfit contract', () => {
  it('accepts only the stable outfit ids and defaults missing values to auto', () => {
    expect(isOutfit('round-glasses')).toBe(true)
    expect(isOutfit('bunny-ears')).toBe(true)
    expect(isOutfit('pumpkin')).toBe(true)
    expect(normalizeOutfit(undefined)).toBe('auto')
    expect(normalizeOutfit('unknown')).toBe('auto')
  })

  it('matches upstream seasonal rules and their boundary cases', () => {
    const local = (year: number, month: number, day: number) => new Date(year, month - 1, day, 12)
    expect(seasonalOutfit(local(2026, 9, 30))).toBe('none')
    expect(seasonalOutfit(local(2026, 10, 1))).toBe('witch-hat')
    expect(seasonalOutfit(local(2026, 11, 1))).toBe('witch-hat')
    expect(seasonalOutfit(local(2026, 11, 2))).toBe('none')
    expect(seasonalOutfit(local(2026, 11, 30))).toBe('none')
    expect(seasonalOutfit(local(2026, 12, 1))).toBe('santa-hat')
    expect(seasonalOutfit(local(2026, 12, 26))).toBe('santa-hat')
    expect(seasonalOutfit(local(2026, 12, 27))).toBe('none')
    expect(seasonalOutfit(local(2026, 12, 30))).toBe('none')
    expect(seasonalOutfit(local(2026, 12, 31))).toBe('party-hat')
    expect(seasonalOutfit(local(2027, 1, 1))).toBe('party-hat')
    expect(seasonalOutfit(local(2027, 1, 2))).toBe('party-hat')
    expect(seasonalOutfit(local(2027, 1, 3))).toBe('none')
    for (const day of [12, 13, 15, 16]) expect(seasonalOutfit(local(2026, 2, day))).toBe('none')
    expect(seasonalOutfit(local(2026, 4, 2))).toBe('none')
    for (const day of [3, 4, 5, 6]) expect(seasonalOutfit(local(2026, 4, day))).toBe('bunny-ears')
    expect(seasonalOutfit(local(2026, 4, 7))).toBe('none')
    expect(seasonalOutfit(local(2027, 3, 26))).toBe('bunny-ears')
    expect(seasonalOutfit(local(2027, 3, 29))).toBe('bunny-ears')
    expect(seasonalOutfit(local(2027, 3, 30))).toBe('none')
    expect(seasonalOutfit(local(2028, 4, 14))).toBe('bunny-ears')
    expect(seasonalOutfit(local(2028, 4, 17))).toBe('bunny-ears')
    expect(seasonalOutfit(local(2028, 4, 18))).toBe('none')
    expect(seasonalOutfit(local(2026, 6, 20))).toBe('none')
    expect(seasonalOutfit(local(2026, 6, 21))).toBe('sunglasses')
    expect(seasonalOutfit(local(2026, 8, 31))).toBe('sunglasses')
    expect(seasonalOutfit(local(2026, 9, 1))).toBe('none')
    expect(resolveOutfit('auto', local(2026, 10, 1))).toBe('witch-hat')
    expect(resolveOutfit('crown', local(2026, 10, 1))).toBe('crown')
  })
})
